stages:
  - deploy
deploy:
  image: 
    name: nurkend/alpine_cert_with_ssh_client_x86
    entrypoint: [""]
  stage: deploy
  tags:
    - deployment
  environment:
    name: production
  only:
    - master
  script:
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "bash /home/testadmin/docker-deploy.sh"
  retry:
    max: 2
    when: runner_system_failure